# Generated by Django 5.2.13 on 2026-04-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invitetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approver',
            field=models.BooleanField(default=False, help_text='다른 회사의 베타 무료 신청 승인 권한. 내일마케팅 등 파트너 직원에게 부여.'),
        ),
    ]
