# Generated by Django 5.2.13 on 2026-04-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assignment_weight',
            field=models.PositiveIntegerField(default=1, help_text='비율 기반 배정 시 가중치. 0 = 비율 배정에서 제외 (단, 다른 전략에선 그대로 후보).'),
        ),
    ]
