# Generated by Django 5.2.13 on 2026-04-22 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('plan', models.CharField(choices=[('trial', 'Trial'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='trial', max_length=20)),
                ('billing_status', models.CharField(choices=[('active', '활성'), ('past_due', '연체'), ('canceled', '해지'), ('trial', '체험중'), ('read_only', '읽기전용')], default='trial', max_length=20)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Seoul', max_length=50)),
                ('industry_preset', models.CharField(blank=True, max_length=20)),
                ('logo_url', models.URLField(blank=True)),
                ('is_internal_test', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
