# Generated by Django 5.2.13 on 2026-04-22 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_on', models.BooleanField(default=False)),
                ('weekdays', models.JSONField(default=list, help_text='[0..6] 월=0')),
                ('time_start', models.TimeField(default='09:00')),
                ('time_end', models.TimeField(default='18:00')),
                ('tie_breaker', models.CharField(choices=[('round_robin', 'Round Robin'), ('least_loaded', 'Least Loaded')], default='round_robin', max_length=20)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_config', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(max_length=20)),
                ('portone_billing_key', models.CharField(blank=True, max_length=200)),
                ('pg_provider', models.CharField(default='tosspayments', max_length=30)),
                ('next_billing_at', models.DateTimeField(blank=True, null=True)),
                ('usage_leads_month', models.IntegerField(default=0)),
                ('usage_sms_month', models.IntegerField(default=0)),
                ('usage_storage_mb', models.IntegerField(default=0)),
                ('cycle_start', models.DateField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', '대기'), ('paid', '결제완료'), ('failed', '실패'), ('refunded', '환불')], default='pending', max_length=20)),
                ('portone_payment_id', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
