# Generated by Django 5.2.13 on 2026-04-28 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_assignmentconfig_last_assigned_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='denial_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='billing_status',
            field=models.CharField(choices=[('pending_approval', '승인 대기'), ('granted_free', '무료 사용 (승인됨)'), ('denied', '신청 거부'), ('active', '활성 (유료)'), ('past_due', '연체'), ('canceled', '해지'), ('trial', '체험중'), ('read_only', '읽기전용')], default='pending_approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='basic', max_length=20),
        ),
    ]
