# Generated by Django 5.2.13 on 2026-04-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_approved_at_company_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentconfig',
            name='weighted_cursor',
            field=models.PositiveBigIntegerField(default=0, help_text='비율 기반 배정 시 시퀀스 카운터. 매 배정마다 +1.'),
        ),
        migrations.AlterField(
            model_name='assignmentconfig',
            name='tie_breaker',
            field=models.CharField(choices=[('round_robin', '순서대로 (라운드 로빈)'), ('least_loaded', '오늘 적게 받은 사람'), ('weighted', '비율 기반 (상담사별 가중치)')], default='round_robin', max_length=20),
        ),
    ]
