# Generated by Django 5.2.13 on 2026-04-24 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_assignmentconfig_last_assigned_agent'),
        ('leads', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '대기'), ('done', '완료'), ('missed', '미처리')], default='pending', max_length=20)),
                ('reminder_sent', models.BooleanField(db_index=True, default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_callbacks', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='leads.lead')),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['agent', 'status', 'scheduled_at'], name='communicati_agent_i_8bfe4b_idx'), models.Index(fields=['company', 'status', 'scheduled_at'], name='communicati_company_00e27b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(help_text='변수: {name} {phone} {fields.키}')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('alimtalk', '알림톡')], default='sms', max_length=20)),
                ('variables', models.JSONField(blank=True, default=list, help_text="['name','phone',...]")),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='communicati_company_79b879_idx')],
            },
        ),
    ]
