# Generated by Django 5.2.13 on 2026-04-22 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_assignmentconfig_billing_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('received', '리드 수신'), ('status_change', '상태 변경'), ('memo', '메모'), ('sms_sent', 'SMS 발송'), ('alimtalk_sent', '알림톡 발송'), ('callback_scheduled', '콜백 예약'), ('noti_sent', 'NOTI 전송'), ('noti_failed', 'NOTI 실패'), ('assigned', '배정'), ('reassigned', '재배정'), ('field_changed', '필드 변경')], max_length=30)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', '접수'), ('contacted', '상담중'), ('qualified', '선별중'), ('negotiating', '진행중'), ('won', '결과-성사'), ('lost', '결과-실패')], db_index=True, default='new', max_length=20)),
                ('assignment_type', models.CharField(choices=[('auto', '자동'), ('manual', '수동'), ('unassigned', '미배정')], default='unassigned', max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('phone_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('fields', models.JSONField(blank=True, default=dict)),
                ('noti_status', models.CharField(choices=[('ok', '정상'), ('failed', '실패'), ('failed_cleared', '조치완료'), ('n/a', '해당없음')], default='n/a', max_length=20)),
                ('noti_last_error', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('external_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_leads', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='leads.lead')),
                ('intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
