# Generated by Django 5.2.13 on 2026-04-22 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='sources.source'),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='leads.lead'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'status', '-received_at'], name='leads_lead_company_814a59_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'agent', 'status'], name='leads_lead_company_91600e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'source', '-received_at'], name='leads_lead_company_6c886a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'phone_hash'], name='leads_lead_company_b80bff_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'noti_status'], name='leads_lead_company_795618_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineentry',
            index=models.Index(fields=['lead', '-at'], name='leads_timel_lead_id_4eea99_idx'),
        ),
    ]
