# Generated by Django 5.2.13 on 2026-04-24 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_assignmentconfig_last_assigned_agent'),
        ('leads', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineentry',
            name='type',
            field=models.CharField(choices=[('received', '리드 수신'), ('status_change', '상태 변경'), ('memo', '메모'), ('sms_sent', 'SMS 발송'), ('alimtalk_sent', '알림톡 발송'), ('callback_scheduled', '콜백 예약'), ('noti_sent', 'NOTI 전송'), ('noti_failed', 'NOTI 실패'), ('assigned', '배정'), ('reassigned', '재배정'), ('field_changed', '필드 변경'), ('blacklisted', '블랙리스트 추가'), ('blacklist_hit', '블랙리스트 차단')], max_length=30),
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_hash', models.CharField(max_length=64)),
                ('phone_masked', models.CharField(help_text='010-****-1234 형식', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('source_lead', models.ForeignKey(blank=True, help_text='이 리드를 계기로 추가된 경우 연결', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_blacklists', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'phone_hash'], name='leads_black_company_65918f_idx')],
                'unique_together': {('company', 'phone_hash')},
            },
        ),
    ]
