# Generated by Django 5.2.13 on 2026-04-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_timelineentry_type_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineentry',
            name='type',
            field=models.CharField(choices=[('received', '리드 수신'), ('status_change', '상태 변경'), ('memo', '메모'), ('sms_sent', 'SMS 발송'), ('alimtalk_sent', '알림톡 발송'), ('callback_scheduled', '콜백 예약'), ('noti_sent', 'NOTI 전송'), ('noti_failed', 'NOTI 실패'), ('assigned', '배정'), ('reassigned', '재배정'), ('field_changed', '필드 변경'), ('blacklisted', '블랙리스트 추가'), ('blacklist_hit', '블랙리스트 차단'), ('call_initiated', '통화 시도')], max_length=30),
        ),
    ]
