# Generated by Django 5.2.13 on 2026-04-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='noti_webhook_url',
            field=models.URLField(blank=True, help_text="리드 수신 후 외부 시스템 알림용 Webhook URL (선택). 실패 시 '빨간불'", max_length=500),
        ),
    ]
